### Register new user
POST http://localhost/api/v1/users
Content-Type: application/json

{
  "firstName": "ddd",
  "lastName": "ddd",
  "email": "ddd@gmail.com"
}

### Get all users
GET http://localhost/api/v1/users
Accept: application/json

### Get user by Id
GET http://localhost/api/v1/users/1
Accept: application/json

### Delete user by Id
DELETE http://localhost/api/v1/users/3
Accept: application/json




